import Head from 'next/head'
import { ReactNode } from 'react'
import Footer from './Footer'
import Header from './header/index'

function Layout({ children, title }: any) {
  return (
    <div className="content">
      <Head>
        <title>{title ? title + ' - Web' : 'Web'}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <main className='mx-[20px] md:mx-[80px]'>{children}</main>

      <Footer />
    </div>
  )
}

export default Layout
